---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: k8s-owner-pod-reader
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-owner-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-owner-pod-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-owner-pod-reader
subjects:
  - kind: ServiceAccount
    name: k8s-owner-pod-reader
    namespace: k8s-ownership
---